apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    mathcLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec: 
      containers:
        - name: users
          image: masterbogdan/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"